//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.27 at 07:32:12 PM CEST 
//


package dualstrike.configuration.model;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:strike-devices:configuration}Infos"/>
 *         &lt;sequence>
 *           &lt;element name="device" type="{urn:strike-devices:configuration}field"/>
 *           &lt;element name="version" type="{urn:strike-devices:configuration}field"/>
 *           &lt;element name="page" type="{urn:strike-devices:configuration}Page" maxOccurs="unbounded"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="def-lang-version" use="required" type="{http://www.w3.org/2001/XMLSchema}int" fixed="1" />
 *       &lt;attribute name="lang" use="required" type="{http://www.w3.org/2001/XMLSchema}language" />
 *       &lt;attribute name="prefix" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "title",
    "help",
    "device",
    "version",
    "page"
})
@XmlRootElement(name = "configuration")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
public class Configuration {

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected List<Info> title;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected List<Info> help;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected byte device;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected byte version;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected List<Page> page;
    @XmlAttribute(name = "def-lang-version", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected int defLangVersion;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected String lang;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected String prefix;

    /**
     * Gets the value of the title property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the title property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Info }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public List<Info> getTitle() {
        if (title == null) {
            title = new ArrayList<Info>();
        }
        return this.title;
    }

    /**
     * Gets the value of the help property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the help property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHelp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Info }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public List<Info> getHelp() {
        if (help == null) {
            help = new ArrayList<Info>();
        }
        return this.help;
    }

    /**
     * Gets the value of the device property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public byte getDevice() {
        return device;
    }

    /**
     * Sets the value of the device property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setDevice(byte value) {
        this.device = value;
    }

    /**
     * Gets the value of the version property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public byte getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setVersion(byte value) {
        this.version = value;
    }

    /**
     * Gets the value of the page property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the page property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Page }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public List<Page> getPage() {
        if (page == null) {
            page = new ArrayList<Page>();
        }
        return this.page;
    }

    /**
     * Gets the value of the defLangVersion property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public int getDefLangVersion() {
        return defLangVersion;
    }

    /**
     * Sets the value of the defLangVersion property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setDefLangVersion(int value) {
        this.defLangVersion = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-27T07:32:12+02:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setPrefix(String value) {
        this.prefix = value;
    }

}
