//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.19 at 11:06:42 AM CET 
//


package mccf.definition;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *       An element of this kind imposes two constraints on the configuration:
 *         -The containing option can only be activated if the referred
 *          setting is set.
 *         -If the containing option is the current selection of its
 *          containing choice, the referred setting is set fix, e.g. all other
 *          settings are deactivated.
 *          
 *       To prevent cascading changes and clashing requirements, the
 *       following cases must not occur (which the application has to check):
 *         -A setting A is being required by a setting B (A may be equal to B)
 *          and A requires a setting different from B.
 *         -For a pair of settings A and B, A is required
 *          by a setting C, B is required by a setting D and C and D are
 *          different settings.
 *     
 * 
 * <p>Java class for Requires complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Requires">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{urn:strike-devices:configuration}References"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Requires", propOrder = {
    "_boolean",
    "choice",
    "integer"
})
@XmlSeeAlso({
    IntegerRequires.class,
    BooleanRequires.class,
    OptionRequires.class
})
public abstract class Requires {

    @XmlElement(name = "boolean")
    protected BooleanReference _boolean;
    protected ChoiceReference choice;
    protected IntegerReference integer;

    /**
     * Gets the value of the boolean property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanReference }
     *     
     */
    public BooleanReference getBoolean() {
        return _boolean;
    }

    /**
     * Sets the value of the boolean property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanReference }
     *     
     */
    public void setBoolean(BooleanReference value) {
        this._boolean = value;
    }

    /**
     * Gets the value of the choice property.
     * 
     * @return
     *     possible object is
     *     {@link ChoiceReference }
     *     
     */
    public ChoiceReference getChoice() {
        return choice;
    }

    /**
     * Sets the value of the choice property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChoiceReference }
     *     
     */
    public void setChoice(ChoiceReference value) {
        this.choice = value;
    }

    /**
     * Gets the value of the integer property.
     * 
     * @return
     *     possible object is
     *     {@link IntegerReference }
     *     
     */
    public IntegerReference getInteger() {
        return integer;
    }

    /**
     * Sets the value of the integer property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegerReference }
     *     
     */
    public void setInteger(IntegerReference value) {
        this.integer = value;
    }

}
