// C:\Users\Michael\Desktop\HID Report Descriptor Editor\mame.h


char ReportDescriptor[230] = {
    0x05, 0x01,                    // USAGE_PAGE (Generic Desktop)
    0x09, 0x06,                    // USAGE (Keyboard)
    0xa1, 0x01,                    // COLLECTION (Application)
    0x05, 0x07,                    //   USAGE_PAGE (Keyboard)
    0x15, 0x00,                    //   LOGICAL_MINIMUM (0)
    0x25, 0x01,                    //   LOGICAL_MAXIMUM (1)
    0x35, 0x00,                    //   PHYSICAL_MINIMUM (0)
    0x45, 0x01,                    //   PHYSICAL_MAXIMUM (1)
    0x75, 0x01,                    //   REPORT_SIZE (1)
    0x95, 0x01,                    //   REPORT_COUNT (1)
    0x85, 0x01,                    //   REPORT_ID (1)
    0x09, 0x52,                    //   USAGE (Keyboard UpArrow)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x4f,                    //   USAGE (Keyboard RightArrow)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x51,                    //   USAGE (Keyboard DownArrow)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x50,                    //   USAGE (Keyboard LeftArrow)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0xe1,                    //   USAGE (Keyboard LeftShift)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x1b,                    //   USAGE (Keyboard x and X)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x1c,                    //   USAGE (Keyboard y and Y)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x81, 0x01,                    //   INPUT (Cnst,Ary,Abs)
    0x09, 0xe0,                    //   USAGE (Keyboard LeftControl)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0xe2,                    //   USAGE (Keyboard LeftAlt)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x2c,                    //   USAGE (Keyboard Spacebar)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0xe1,                    //   USAGE (Keyboard LeftShift)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x22,                    //   USAGE (Keyboard 5 and %)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x1e,                    //   USAGE (Keyboard 1 and !)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x13,                    //   USAGE (Keyboard p and P)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x81, 0x01,                    //   INPUT (Cnst,Ary,Abs)
    0x85, 0x02,                    //   REPORT_ID (2)
    0x09, 0x15,                    //   USAGE (Keyboard r and R)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x0a,                    //   USAGE (Keyboard g and G)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x09,                    //   USAGE (Keyboard f and F)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x07,                    //   USAGE (Keyboard d and D)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x1a,                    //   USAGE (Keyboard w and W)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x0e,                    //   USAGE (Keyboard k and K)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x0c,                    //   USAGE (Keyboard i and I)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x81, 0x01,                    //   INPUT (Cnst,Ary,Abs)
    0x09, 0x04,                    //   USAGE (Keyboard a and A)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x16,                    //   USAGE (Keyboard s and S)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x14,                    //   USAGE (Keyboard q and Q)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x1a,                    //   USAGE (Keyboard w and W)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x23,                    //   USAGE (Keyboard 6 and ^)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x1f,                    //   USAGE (Keyboard 2 and @)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x13,                    //   USAGE (Keyboard p and P)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x81, 0x01,                    //   INPUT (Cnst,Ary,Abs)
    0x85, 0x03,                    //   REPORT_ID (3)
    0x09, 0x52,                    //   USAGE (Keyboard UpArrow)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x4f,                    //   USAGE (Keyboard RightArrow)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x51,                    //   USAGE (Keyboard DownArrow)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x50,                    //   USAGE (Keyboard LeftArrow)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x3b,                    //   USAGE (Keyboard F2)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x3c,                    //   USAGE (Keyboard F3)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x81, 0x01,                    //   INPUT (Cnst,Ary,Abs)
    0x81, 0x01,                    //   INPUT (Cnst,Ary,Abs)
    0x09, 0x28,                    //   USAGE (Keyboard Return (ENTER))
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x29,                    //   USAGE (Keyboard ESCAPE)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x81, 0x01,                    //   INPUT (Cnst,Ary,Abs)
    0x81, 0x01,                    //   INPUT (Cnst,Ary,Abs)
    0x09, 0x26,                    //   USAGE (Keyboard 9 and ()
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x09, 0x2b,                    //   USAGE (Keyboard Tab)
    0x81, 0x00,                    //   INPUT (Data,Ary,Abs)
    0x81, 0x01,                    //   INPUT (Cnst,Ary,Abs)
    0x81, 0x01,                    //   INPUT (Cnst,Ary,Abs)
    0xc0,                          // END_COLLECTION
    0x05, 0x0c,                    // USAGE_PAGE (Consumer Devices)
    0x09, 0x01,                    // USAGE (Consumer Control)
    0xa1, 0x01,                    // COLLECTION (Application)
    0x85, 0x04,                    //   REPORT_ID (4)
    0x15, 0x00,                    //   LOGICAL_MINIMUM (0)
    0x25, 0x01,                    //   LOGICAL_MAXIMUM (1)
    0x35, 0x00,                    //   PHYSICAL_MINIMUM (0)
    0x45, 0x01,                    //   PHYSICAL_MAXIMUM (1)
    0x09, 0xe9,                    //   USAGE (Volume Up)
    0x09, 0xea,                    //   USAGE (Volume Down)
    0x75, 0x01,                    //   REPORT_SIZE (1)
    0x95, 0x02,                    //   REPORT_COUNT (2)
    0x81, 0x02,                    //   INPUT (Data,Var,Abs)
    0x95, 0x06,                    //   REPORT_COUNT (6)
    0x81, 0x01,                    //   INPUT (Cnst,Ary,Abs)
    0xc0                           // END_COLLECTION
};

